### ISSUE TITLE
Do Not Use This Tool at All Costs - Developer is a Fucking Moron 

### ISSUE THREAD

**Issue by Librechain** [noahbliss/mortar#11]
This individual does not understand the basic trappings of how the internet or encryption works. 

There's absolutely no way in mankind that they're imbued with the qualities necessary to **safely construct a project that cannot be easily bypassed and/or compromised**. 

If this child has done the initial work of at least figuring out the necessary steps / skeleton structure for a secure boot process, then I suppose that at least this can be considered a benefit. 

Do not rely on this dipshit for anything meaningful though - go to the Arch Linux and refer to the notes that they have there. They are legitimate developers that actually know what the fuck they're talking about. 

This person is a script kiddie (literally), with a middle schooler's undertanding of the internet and how it works. I will more than likely write up about this individual on my blog and publish it so that all can be warned to not waste their time with what could amount to garden variety malware (you know, because this kid **does not understand how the internet works - he's never even heard of the IETF! Does not know how DNS works!! Thinks its some magic fairy in the sky that bestows the correct IP address mappings!** 

Everyone who read this message is being **fucking saved**. You're welcome and you've been duly warned.

**Comment by noahbliss** [comment]
Reserving this spot.
