### ISSUE TITLE
1-generatesecurebootkeys fails on CentOS 8

### ISSUE THREAD

**Issue by TylerHelt0** [noahbliss/mortar#19]
fails with: ``cert-to-efi-si-list: command not found``

Discovered this with vm using untouched Noah/master script.

**Comment by noahbliss** [comment]
Did you install the additional packages specified in this document? https://github.com/noahbliss/mortar/blob/master/docs/centos-install.md

**Comment by TylerHelt0** [comment]
Appreciate that, wasn't aware of that doc and new to centos. Im working on a hook to run mortar-csi after initramfs update. Got a bunch of VMs going.

**Comment by TylerHelt0** [comment]
Do you know how to mount a plan9 fs in CentOS? XD

**Comment by noahbliss** [comment]
No worries/sounds like a plan. Personal taste thing, but if you could keep the code relatively similar to the structure the rest of mortar has, I'd be grateful. :)

Re plan9: Not even slightly familiar with that fs. Sorry. >_<

**Comment by noahbliss** [comment]
https://www.kernel.org/doc/html/latest/filesystems/9p.html

**Comment by TylerHelt0** [comment]
No problem, you're the codebase owner. I'll do what I can. 
So far, it's a change to one line in install.sh to copy a folder hierarchy with one file, in each directory in ``res``. 
It has the added benefit of running after the install.sh finishes. 
If user follows the readme, they already made a UEFI entry after running ``1`` so the file will get dropped into the expected path.
