### ISSUE TITLE
Issue booting in secure mode with Promxox kernels >= 5.19

### ISSUE THREAD

**Issue by blaze1st** [noahbliss/mortar#28]
Installing and configuring mortar works perfectly with Proxmox 5.15.* kernels, however, using the latest 5.19 and 6.1 kernels for Proxmox result in boot hang up.

**Comment by noahbliss** [comment]
I've had multiple reports of this and will be investigating.

**Comment by dinvlad** [comment]
Any updates on this?

**Comment by dinvlad** [comment]
Any more updates on this?

**Comment by noahbliss** [comment]
Not yet. I have one system with proxmox I can't afford to mess with, and have other active projects of a higher priority at the moment. PRs are welcome if someone else wants to tackle this first.

**Comment by noahbliss** [comment]
Per the telegram chat, this does seem to be related to proxmox specifically though and not the kernel version. Not sure what they are doing, it might be a mechanism for installation, could be mods they made to the kernel, etc.

**Comment by duracell** [comment]
Is it possible to put a warning in the README?
I checked there and thought an upgrade would be possible without any problem :(

**Comment by noahbliss** [comment]
https://forum.proxmox.com/threads/mortar-secureboot-luks-framework-broken-with-pve-kernel-5-19.132131/

if y'all wouldn't mind posting in this thread to increase awareness for the proxmox devs, I'd be grateful

**Comment by ioctl2** [comment]
I, too, ran into this issue when I tried to upgrade the kernel on one of my Proxmox instances. I put it on the backburner for a while, and have been keeping an eye on this issue.

As a workaround for Proxmox hosts running kernels 6.x, what are your thoughts on doing something like [this ](https://www.reddit.com/r/debian/comments/154b4iv/theft_proof_installation_of_debian_12_on_thinkpad/), @noahbliss?
Relevant part:
```
apt install clevis-tpm2 clevis-initramfs
clevis luks bind -d /dev/nvme0n1p3 tpm2 '{"pcr_ids":"7,14"}'
```
Aside from the issue of choice of PCRs and general hardening, this appears to work on a fresh Debian 12 Bookworm install, including with a subsequent conversion to Proxmox.

The LUKS system partition gets automatically unlocked via the TPM (tested on VMWare Workstation) as expected. Upon removing the vTPM in my testing, it would no longer unlock (also as expected). Finally, reattaching a TPM and rebinding will once again enable automatic unlocking during boot.

I am going to test on bare metal in the coming days.

**Comment by noahbliss** [comment]
@ioctl2 this sounds promising, if they (the clevis team/clevis-initramfs devs) implemented this all correctly, could potentially gut all of the debian initramfs bits of mortar and essentially just use their package for that portion. 

At the moment, I don't have the bandwidth to test this unfortunately, but please report back on your findings. You may want to remove/modify the parts of mortar's initramfs work to ensure there aren't conflicts.

**Comment by noahbliss** [comment]
https://pulsesecurity.co.nz/advisories/tpm-luks-bypass this article is the only reason I added all the qualifiers to the last message.

**Comment by ioctl2** [comment]
Thank you for the input.

Quick follow up: I forgot that Secure Boot isn't enabled by default for UEFI VMWare Workstation VMs (also unhelpfully grayed out when a debian Linux template is selected), so the testing I did worked with Secure Boot disabled. Enabling Secure Boot breaks the boot process with this error (on a VM and a Dell Wyse 5070 thin client):

![image](https://github.com/noahbliss/mortar/assets/111940467/c92dd207-7bff-4b0c-8612-adc3f0d4bba5)

**Comment by ioctl2** [comment]
I just tried the install again with the latest proxmox release and kernel 6.5 (they recently released Proxmox 8.1 with kernel 6.5). Their kernel is now signed. However, still no dice. On my test machine it hangs after installing the kernel and rebooting.
![image](https://github.com/noahbliss/mortar/assets/111940467/a67bb9e8-dbc4-4cee-9508-b2cc22d18ea4)

**Comment by noahbliss** [comment]
Yeah. They did something to it and I don't know what. It seems using the vanilla debian kernel works though.

**Comment by ioctl2** [comment]
Do you mean you're running Proxmox with the vanilla kernel? If so, are any features missing/broken that you know of?

**Comment by noahbliss** [comment]
Yes, I am running the debian vanilla kernel, and as far as I can tell, nothing major is broken. Caveat: my setup currently is relatively standard. But containers/vms of various varieties seem to run without critical issues or noticeable performance loss.

**Comment by noahbliss** [comment]
This is resolved with the latest batch of kernels. I have updated the relevant portion of the readme with this commit: https://github.com/noahbliss/mortar/commit/8914d8e8900ad5bfb4c99f64a5d7551fa22051ec. More details are available on the new page at the top under "warning": [proxmox-install.md](https://github.com/noahbliss/mortar/blob/master/docs/proxmox-install.md)
