### ISSUE TITLE
Using bin bash everywhere

### ISSUE THREAD

**Issue by inf3rno** [noahbliss/mortar#3]
I am not sure if this is intentional, but I see sometimes bin/bash and bin/sh in the code. Afaik bin/sh can be dash too on some systems, so it would be better to use bash only unless you have a good reason to use sh.

**Comment by noahbliss** [comment]
Hey @inf3rno thanks for the comment. I took a quick stroll through the code and it seems the only non-bash shebangs in the code are in the distribution-specific initramfs hooks and scripts. For these files, specialization to each distribution is necessary and I did my best to preserve what was "standard" in common initramfs scripts for that specific distribution. Moreover, scripts placed inside the initramfs do not have bash at all by default in debian, clevis requires that binary be added first. I'd like to eventually move off of clevis dependency for tpm2 and trim down our required binary list (and attack surface), not increase our dependency on bash. 

Does that make sense? Happy to elaborate.

**Comment by inf3rno** [comment]
No that's fine.
