### ISSUE TITLE
Line 61: Cryptsetup: command not found

### ISSUE THREAD

**Issue by jtyvy8080** [noahbliss/mortar#37]
On a fresh debian 12 libvirt virtual machine (wanted to test before deciding to switch from fedora)

 getting error on line 61 when running script

 1-generatesecurebootkeys.sh

Line 61: Cryptsetup: command not found

**Comment by noahbliss** [comment]
Did you select disk encryption when installing debian? Can I see your etc fstab?

**Comment by jtyvy8080** [comment]
Yes luks during install

Fstab details;

/dev/mapper/debian--vg-root  /     ext4 errrors=remount-ro 0

UUID=long uuid    /boot ext2 defaults 0 2

UUID=long uuid    /boot/efi vfat umask=0077 0 1
/dev/mappet/debian--vg-swap_1   none swap sw 0 0

/dev/sr0   /media/cdrom udf,iso9660 user,noauto    0 0

**Comment by noahbliss** [comment]
Got it. So you have a crypttab file as well? It's very unusual that luks would be working without cryptsetup being available. Maybe your path isn't including it? I would check to be sure that the package is actually installed.

**Comment by jtyvy8080** [comment]
Yes luks during install

Fstab details;

/dev/mapper/debian--vg-root  /     ext4 errrors=remount-ro 0

UUID=long uuid    /boot ext2 defaults 0 2

UUID=long uuid    /boot/efi vfat umask=0077 0 1
/dev/mappet/debian--vg-swap_1   none swap sw 0 0

/dev/sr0   /media/cdrom udf,iso9660 user,noauto    0 0

/etc/crypttab

vda3_crypt UUID    none luks,discard

**Comment by jtyvy8080** [comment]
Yes, you were right. sbin not in path.

I have two Debian 12 instances, one with the correct path and one without. They are both fresh installs from the same .iso

 Any idea what would cause that to occur?

**Comment by noahbliss** [comment]
Nah, I've seen it a few times on deb/ubuntu, but in any case the cause isn't mortar. Glad you got it sorted though!

**Comment by vbooka1** [comment]
> Any idea what would cause that to occur?

Upgrading privileges from user to root using `su` instead of `su -l` keeps user's PATH which by default does not have `/sbin`
