### ISSUE TITLE
Feature Request: For TPM binding, only ask for LUKS passphrase once

### ISSUE THREAD

**Issue by noahbliss** [noahbliss/mortar#5]
Step 3 with TPM binding asks for the LUKS passphrase twice. Writing this to remind myself to investigate ways to only ask once. Maybe add some logic in there to test it before using it too.

**Comment by noahbliss** [comment]
Closing this for now. It seems to only ask twice if mortar was already installed at one point and it needs to clean up. As this is a limited use-case, it can be a future non-functionality-critical improvement.

**Comment by TylerHelt0** [comment]
You could store the password from stdin to a keyfile on the tpmramfs you use to create the new key, than supply the keyfile to the cryptsetup command.
If a user happens to change BIOS settings temporarily this can be annoying, or if they are making changes to the software. ;)

**Comment by noahbliss** [comment]
Heh @TylerHelt0 trust me I know how annoying it can be. Especially when I'm not doing as sophisticated a job at error handling as I could be and you fat finger the second prompt. That could work. I'll see about making a branch to test. Not being able to snapshot uefi systems on KVM is so frustrating.
